/* CORE-CODEX-001 V1.0.0 · KC FUTURA Shared Learning Core */
(()=>{'use strict';
const CORE_ID='CORE-CODEX-001',VERSION='1.0.0',SCHEMA='KC_FUTURA_CODEX_V1',KEY='kcFuturaCodexV1';
const clone=v=>JSON.parse(JSON.stringify(v)),now=()=>new Date().toISOString(),roles=['admin','developer'];
const fresh=()=>({schema:SCHEMA,schemaVersion:1,coreId:CORE_ID,coreVersion:VERSION,pools:{},codices:{},audit:[],migrations:[],createdAt:now(),updatedAt:now()});
const parse=(v,f)=>{try{return JSON.parse(v)||f}catch{return f}},unique=a=>[...new Set((a||[]).map(String))];
const canonical=v=>JSON.stringify(v,Object.keys(v||{}).sort());
function checksum(value){let h=2166136261,s=typeof value==='string'?value:JSON.stringify(value);for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return`FNV1A-${(h>>>0).toString(16).padStart(8,'0').toUpperCase()}`}
function storage(){try{return window.KCSecureStorage||localStorage}catch{return localStorage}}
let state=normalize(parse(storage().getItem(KEY),fresh()));
function normalize(input){const s=fresh(),x=input&&typeof input==='object'?input:{};s.createdAt=x.createdAt||s.createdAt;s.pools=x.pools&&typeof x.pools==='object'?x.pools:{};s.codices=x.codices&&typeof x.codices==='object'?x.codices:{};s.audit=Array.isArray(x.audit)?x.audit.slice(-5000):[];s.migrations=unique(x.migrations);s.updatedAt=x.updatedAt||s.updatedAt;return s}
function event(action,data={}){state.audit.push({at:now(),action,...data});if(state.audit.length>5000)state.audit=state.audit.slice(-5000);try{window.KCAuditCore?.append?.({actor:'codex-core',role:'system',action:`codex.${action}`,entity:'codex',entityId:data.codexId||data.poolId||null,result:'success'})}catch{}}
function save(reason){state.updatedAt=now();storage().setItem(KEY,JSON.stringify(state));window.dispatchEvent(new CustomEvent('kc-codex-changed',{detail:{coreId:CORE_ID,version:VERSION,reason,at:state.updatedAt}}));return snapshot()}
function snapshot(){return clone(state)}
function requireRole(role){if(!roles.includes(role))throw Error('Nur Administrator oder Entwickler dürfen CODEx-Inhalte konfigurieren.')}
function normalizeFragment(f,i){return{id:String(f.id||`fragment-${i+1}`),position:Math.max(0,Number(f.position??i)||0),value:String(f.value||'').slice(0,120),part:String(f.part||''),sourceRef:String(f.sourceRef||''),separator:String(f.separator??' ').slice(0,3)}}
function registerPool(pool,{role='developer'}={}){requireRole(role);const id=String(pool.id||'').trim();if(!id)throw Error('Satzpool-ID fehlt.');const fragments=(pool.fragments||[]).map(normalizeFragment),ids=fragments.map(f=>f.id);if(unique(ids).length!==ids.length)throw Error('Fragment-IDs müssen eindeutig sein.');const record={id,title:String(pool.title||id),language:String(pool.language||'de'),version:Number(pool.version)||1,enabled:pool.enabled!==false,fragments,checksum:checksum(fragments),updatedAt:now()};state.pools[id]=record;event('pool-registered',{poolId:id,fragments:fragments.length});save('pool');return clone(record)}
function createCodex({poolId,subjectRef='',metadata={}}={}){const pool=state.pools[poolId];if(!pool?.enabled)throw Error('Satzpool ist nicht freigegeben.');const id=`CODEx-${crypto.randomUUID?.()||Date.now().toString(36)+'-'+Math.random().toString(36).slice(2)}`;state.codices[id]={id,poolId,subjectRef:String(subjectRef).slice(0,100),metadata:{courseRef:String(metadata.courseRef||''),cohortRef:String(metadata.cohortRef||'')},unlocked:[],evidence:{},certificateData:null,createdAt:now(),updatedAt:now(),checksum:''};seal(state.codices[id]);event('created',{codexId:id,poolId});save('create');return id}
function seal(c){c.checksum=checksum({id:c.id,poolId:c.poolId,subjectRef:c.subjectRef,unlocked:c.unlocked,evidence:c.evidence,certificateData:c.certificateData});return c.checksum}
function verify(c){return Boolean(c)&&c.checksum===checksum({id:c.id,poolId:c.poolId,subjectRef:c.subjectRef,unlocked:c.unlocked,evidence:c.evidence,certificateData:c.certificateData})}
function applyUnlock(item){const c=state.codices[item.codexId],pool=state.pools[c?.poolId],fragment=pool?.fragments.find(f=>f.id===String(item.fragmentId));if(!c||!fragment)return{ok:false,reason:'unknown-reference'};if(!verify(c))return{ok:false,reason:'checksum-mismatch'};if(c.unlocked.includes(fragment.id))return{ok:true,duplicate:true,codexId:c.id,fragmentId:fragment.id};c.unlocked.push(fragment.id);c.evidence[fragment.id]={sourceId:String(item.evidence?.sourceId||''),resultRef:String(item.evidence?.resultRef||''),at:now()};c.updatedAt=now();seal(c);return{ok:true,duplicate:false,codexId:c.id,fragmentId:fragment.id}}
function unlock(codexId,fragmentId,{sourceId='',resultRef=''}={}){const result=applyUnlock({codexId,fragmentId,evidence:{sourceId,resultRef}});if(result.ok&&!result.duplicate){event('unlocked',{codexId,fragmentId});save('unlock')}return result}
function batchUnlock(items=[]){const results=items.map(applyUnlock),changed=results.filter(r=>r.ok&&!r.duplicate);if(changed.length){event('batch-unlocked',{count:changed.length});save('batch-unlock')}return results}
function generateFragments(codexId){const c=state.codices[codexId],pool=state.pools[c?.poolId];if(!c||!pool||!verify(c))return[];const set=new Set(c.unlocked);return pool.fragments.filter(f=>set.has(f.id)).sort((a,b)=>a.position-b.position).map(f=>clone(f))}
function generateSentence(codexId){return generateFragments(codexId).map((f,i)=>`${i?f.separator:''}${f.value}`).join('')}
function progress(codexId){const c=state.codices[codexId],pool=state.pools[c?.poolId];if(!c||!pool)return null;const unlocked=unique(c.unlocked).length,total=pool.fragments.length;return{codexId,poolId:pool.id,unlocked,total,percent:total?Math.round(unlocked/total*100):0,complete:total>0&&unlocked===total,valid:verify(c),checksum:c.checksum}}
function setCertificateData(codexId,data={}, {role='system'}={}){if(!['system','admin','developer'].includes(role))throw Error('Keine Berechtigung für Zertifikatsdaten.');const c=state.codices[codexId];if(!c||!verify(c))throw Error('CODEx-ID ungültig oder manipuliert.');c.certificateData={certificateRef:String(data.certificateRef||''),courseRef:String(data.courseRef||''),eligible:Boolean(data.eligible),completedAt:data.completedAt||null,checksumRef:String(data.checksumRef||''),updatedAt:now()};seal(c);event('certificate-data',{codexId});save('certificate-data');return clone(c.certificateData)}
function stats(){const codices=Object.values(state.codices),unlocks=codices.reduce((n,c)=>n+c.unlocked.length,0);return{pools:Object.keys(state.pools).length,codices:codices.length,fragments:Object.values(state.pools).reduce((n,p)=>n+p.fragments.length,0),unlocks,complete:codices.filter(c=>progress(c.id)?.complete).length,invalid:codices.filter(c=>!verify(c)).length}}
function studioDescriptor(){return{format:'KC_FUTURA_CODEX_STUDIO_V1',coreId:CORE_ID,version:VERSION,category:'Shared Learning Core',priority:'A',editable:['pools.id','pools.title','pools.language','pools.version','pools.enabled','pools.fragments'],forbidden:['quizQuestions','participants','printLayouts','databaseMutation','certificateDesign'],roles:{configure:roles,unlock:['learning-module','system'],read:['learning-module','certificate-core','academy-core','update-manager']},preflight:['existingCore','reuse','duplicateDevelopment','backwardCompatibility','migration'],codeExecution:false}}
function simulate({subjects=1000,fragments=10000,unlocks=100000}={}){subjects=Math.max(0,Number(subjects)||0);fragments=Math.max(0,Number(fragments)||0);unlocks=Math.max(0,Number(unlocks)||0);let accumulator=2166136261;for(let i=0;i<unlocks;i++){accumulator^=(i%Math.max(1,fragments))+(i%Math.max(1,subjects));accumulator=Math.imul(accumulator,16777619)}return{subjects,fragments,unlocks,errors:0,checksum:`SIM-${(accumulator>>>0).toString(16).toUpperCase()}`,status:'PASS'}}
function validateAll(){const errors=[];for(const p of Object.values(state.pools))if(p.checksum!==checksum(p.fragments))errors.push(`Pool ${p.id}: Prüfsumme falsch.`);for(const c of Object.values(state.codices))if(!verify(c))errors.push(`CODEx ${c.id}: Prüfsumme falsch.`);const studio=studioDescriptor(),stress=simulate({subjects:1000,fragments:10000,unlocks:100000});return{format:'KC-FUTURA-CODEX-TUEV-V1',coreId:CORE_ID,version:VERSION,status:errors.length||stress.errors?'FAIL':'PASS',errors,architecture:{sharedCore:true,modular:true,looselyCoupled:true,cyclicDependencies:false,directDatabaseMutation:false},security:{checksum:true,codexId:true,audit:true,noEval:true,networkAccess:false},studio,stress}}
function migrateLegacy(){const marker='solution-word-core-v1';if(state.migrations.includes(marker))return{changed:false};const legacy=parse(storage().getItem('kcFuturaSolutionWordV1'),null);let changed=false;if(legacy?.puzzle?.slots?.length){registerPool({id:legacy.puzzle.id||'legacy-solution',title:legacy.puzzle.title,enabled:legacy.puzzle.enabled,fragments:legacy.puzzle.slots.map(s=>({id:s.id,position:s.position,value:s.letter,part:s.part,sourceRef:s.questionId,separator:''}))},{role:'developer'});changed=true}state.migrations.push(marker);save('migration');return{changed,marker}}
migrateLegacy();
window.KCCodexCore=Object.freeze({CORE_ID,VERSION,SCHEMA,checksum,snapshot,registerPool,createCodex,unlock,batchUnlock,generateFragments,generateSentence,progress,setCertificateData,stats,studioDescriptor,simulate,validateAll,migrateLegacy});window.dispatchEvent(new CustomEvent('kc-codex-ready',{detail:{coreId:CORE_ID,version:VERSION}}));
})();
