import {EDITIONS,ASSET_SETS,GAMES,DIFFICULTIES,assetsFor} from './registries.js';
import {MemoryGame,LightsGame,TicTacToeGame,SlotGame,DiceGame,ConnectFourGame,KitchenSequenceGame} from './games.js?v=2.1.7';
import {GlassBalanceGame} from './glass-balance-game.js?v=2.0.1';
import {MazeGame} from './maze-game.js?v=2.0.0';
import {PremiumDiceGame} from './premium-dice-game.js?v=1.0.0';
import {ServiceTrayGame,KitchenVaultGame,AuctionGame,KitchenRouletteGame} from './premium-trilogy-games.js?v=1.1.0';
import {readTrainingProgress} from './progress-adapter.js';
import {CANDIDATE_TEST_UNLOCKS} from './candidate-config.js';

const $=s=>document.querySelector(s);
$('#editionSelect').innerHTML=Object.values(EDITIONS).map(x=>`<option value="${x.id}">${x.label}</option>`).join('');
const trainingProgress=readTrainingProgress();
const storedEdition=localStorage.getItem('kc-game-edition');
const state={edition:storedEdition==='kc-classic'?'modern-casino':storedEdition||'kc-weihnachtsmarkt',difficulty:'normal',set:'all-assets',game:null,instance:null,score:0,round:1,selected:new Set(),player:null,opponent:null};
const classes={memory:MemoryGame,lights:LightsGame,ttt:TicTacToeGame,slot:SlotGame,dice:PremiumDiceGame,connect4:ConnectFourGame,glass:GlassBalanceGame,kitchen:KitchenSequenceGame,maze:MazeGame,service:ServiceTrayGame,vault:KitchenVaultGame,auction:AuctionGame,roulette:KitchenRouletteGame};
const unlocked=id=>GAMES[id].unlock==='open'||GAMES[id].unlock==='training-complete'&&trainingProgress.trainingComplete||GAMES[id].unlock==='dice-achievement'&&localStorage.getItem('kc-game-achievement:dice')==='1'||GAMES[id].unlock==='connect4-achievement'&&localStorage.getItem('kc-game-achievement:connect4')==='1'||CANDIDATE_TEST_UNLOCKS;
const bestKey=()=>`kc-game-best:${state.game}:${state.difficulty}:${state.edition}`;
const getBest=()=>Number(localStorage.getItem(bestKey())||0);
function currentPool(){return assetsFor(state.edition,state.set)}
function requiredAssetCount(gameId){if(gameId==='memory')return {easy:6,normal:8,pro:10}[state.difficulty];if(gameId==='lights')return {easy:4,normal:6,pro:8}[state.difficulty];if(['ttt','connect4'].includes(gameId))return 2;if(gameId==='slot')return 6;if(gameId==='dice')return 5;return 0}
function resetSelection(){const pool=currentPool();state.selected=new Set(pool.map(x=>x.id));state.player=pool[0]?.id;state.opponent=pool[1]?.id}
function renderEdition(){document.body.dataset.edition=state.edition;$('#editionLabel').textContent=EDITIONS[state.edition].short;$('#editionSelect').value=state.edition;const sets=Object.values(ASSET_SETS).filter(x=>x.editions.includes(state.edition));$('#assetSet').innerHTML=sets.map(x=>`<option value="${x.id}">${x.label}</option>`).join('');if(!sets.some(x=>x.id===state.set))state.set='all-assets';$('#assetSet').value=state.set;localStorage.setItem('kc-game-edition',state.edition)}
function renderAssetStudio(){const pool=currentPool();const options=pool.map(x=>`<option value="${x.id}">${x.label}</option>`).join('');$('#playerAsset').innerHTML=options;$('#opponentAsset').innerHTML=options;$('#playerAsset').value=state.player||pool[0]?.id;$('#opponentAsset').value=state.opponent||pool[1]?.id;$('#assetCatalog').innerHTML=pool.map(x=>`<label class="asset-tile"><input type="checkbox" value="${x.id}" ${state.selected.has(x.id)?'checked':''}><span>${x.src?`<img src="${x.src}" alt="">`:`<b>${x.symbol}</b>`}</span><small>${x.label}</small></label>`).join('');const updateCount=()=>{$('#assetSelectionCount').textContent=`${state.selected.size} ausgewählt · Memory: ${requiredAssetCount('memory')} benötigt`};$('#assetCatalog').querySelectorAll('input').forEach(input=>input.onchange=()=>{input.checked?state.selected.add(input.value):state.selected.delete(input.value);updateCount()});updateCount();$('#assetStudioMessage').textContent='Nur markierte Motive werden im Spiel verwendet.'}
function selectedAssets(gameId){const pool=currentPool(),chosen=pool.filter(x=>state.selected.has(x.id));if(!['ttt','connect4'].includes(gameId))return chosen;const a=pool.find(x=>x.id===state.player&&state.selected.has(x.id))||chosen[0],b=pool.find(x=>x.id===state.opponent&&state.selected.has(x.id)&&x.id!==a?.id)||chosen.find(x=>x.id!==a?.id);return [a,b,...chosen.filter(x=>x.id!==a?.id&&x.id!==b?.id)].filter(Boolean)}
const KARRIERELEITER_CODE_HASH='03ac674216f3e15c761ee1a5e255f067953623c8b388b4459e13f978d7c846f4';
function renderMenu(){state.instance?.destroy?.();state.instance=null;state.game=null;$('#gameView').hidden=true;$('#menuView').hidden=false;$('#gameTitle').textContent='KC Spielpause';$('#statusGame').textContent='Spielauswahl';$('#score').textContent='0';$('#round').textContent='–';$('#best').textContent='–';
const alleAnderenFrei=Object.keys(GAMES).every(id=>unlocked(id));
const karriereleiterKachel=`<button class="game-card ${alleAnderenFrei?'':'locked'}" id="karriereleiterCard" ${alleAnderenFrei?'':'disabled'} title="${alleAnderenFrei?'':'Erst wenn alle anderen Spiele freigeschaltet sind - Rechtsklick für Freischalt-Code.'}"><span>🪜</span><div><strong>KC Karriereleiter</strong><small>Das große Abschluss-Lernmodul · 418 Fragen und Aufgaben.</small><b>${alleAnderenFrei?'Spielen':'🔒 Belohnung nach allen anderen Spielen'}</b></div></button>`;
$('#gameGrid').innerHTML=Object.values(GAMES).map(g=>{const open=unlocked(g.id),testOnly=g.unlock!=='open'&&!trainingProgress.trainingComplete&&CANDIDATE_TEST_UNLOCKS;return `<button class="game-card ${open?'':'locked'}" data-game="${g.id}" ${open?'':'disabled'}><span>${g.icon}</span><div><strong>${g.title}</strong><small>${g.description}</small><b>${testOnly?'Testfreigabe · noch kein Lernerfolg':open?'Spielen':'🔒 Nach Pflichtschulung'}</b></div></button>`}).join('')+karriereleiterKachel;
document.querySelectorAll('[data-game]:not([disabled])').forEach(b=>b.onclick=()=>openGame(b.dataset.game));
document.querySelectorAll('[data-game][disabled]').forEach(b=>b.oncontextmenu=async e=>{e.preventDefault();const eingabe=prompt(`Vierstelliger Freischalt-Code für ${GAMES[b.dataset.game].title}:`);if(eingabe===null)return;const buf=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(eingabe.trim()));const hash=Array.from(new Uint8Array(buf)).map(x=>x.toString(16).padStart(2,'0')).join('');if(hash===KARRIERELEITER_CODE_HASH){localStorage.setItem(`kc-game-manual-unlock:${b.dataset.game}`,'1');renderMenu()}else alert('Code nicht korrekt.')});
const kkarte=$('#karriereleiterCard');
if(kkarte){if(alleAnderenFrei)kkarte.onclick=()=>window.open('../../academy/karriereleiter/index.html','_blank');
kkarte.oncontextmenu=async e=>{if(alleAnderenFrei)return;e.preventDefault();const eingabe=prompt('Vierstelliger Freischalt-Code für die Karriereleiter:');if(eingabe===null)return;const buf=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(eingabe.trim()));const hash=Array.from(new Uint8Array(buf)).map(b=>b.toString(16).padStart(2,'0')).join('');if(hash===KARRIERELEITER_CODE_HASH){Object.keys(GAMES).forEach(id=>localStorage.setItem(`kc-game-manual-unlock:${id}`,'1'));renderMenu()}else alert('Code nicht korrekt.')}}}
function report(x={}){if(x.score!==undefined){state.score=x.score;$('#score').textContent=x.score;if(state.game){const next=Math.max(getBest(),Number(x.score)||0);localStorage.setItem(bestKey(),String(next));$('#best').textContent=next}}if(x.round!==undefined){state.round=x.round;$('#round').textContent=x.round}if(x.message)$('#message').textContent=x.message}
function finish({score,message,achievement=false}){const old=getBest(),next=Math.max(old,score);localStorage.setItem(bestKey(),String(next));if(state.game==='dice'&&achievement)localStorage.setItem('kc-game-achievement:dice','1');if(state.game==='connect4'&&score>0)localStorage.setItem('kc-game-achievement:connect4','1');$('#best').textContent=next;report({score,message});$('#result').hidden=false;$('#resultText').textContent=message}
function openGame(id){const assets=selectedAssets(id),needed=requiredAssetCount(id);if(assets.length<needed){state.game=id;renderAssetStudio();$('#assetStudioMessage').textContent=`Bitte mindestens ${needed} Motive für ${GAMES[id].title} markieren. Aktuell: ${assets.length}.`;$('#assetDialog').showModal();return}state.game=id;$('#menuView').hidden=true;$('#gameView').hidden=false;$('#result').hidden=true;$('#gameTitle').textContent=`${GAMES[id].title} · ${EDITIONS[state.edition].label}`;$('#statusGame').textContent=GAMES[id].title.replace('KC ','');$('#score').textContent='0';$('#round').textContent='1';$('#best').textContent=getBest();const Game=classes[id];state.instance=new Game({host:$('#gameHost'),assets,difficulty:state.difficulty,edition:state.edition,status:report,finish});state.instance.start()}
function help(){const g=state.game?GAMES[state.game].title:'KC Spielpause';$('#helpTitle').textContent=`Hilfe · ${g}`;$('#helpText').textContent=state.game?'Wähle Leicht, Normal oder Profi. Punkte, Runde, Bestwert, Hilfe, Ton, Spielauswahl und Neustart befinden sich in allen Spielen an derselben Stelle.':'Im Prüfkandidaten sind alle zwölf Spiele sofort testbar. Über „Motive & Duell wählen“ lassen sich Mitglieder, Avatare, Weihnachtsmarkt-Symbole, Gegenstände und Zahlen frei kombinieren.';$('#helpDialog').showModal()}
$('#editionSelect').onchange=e=>{state.edition=e.target.value;renderEdition();resetSelection();renderMenu()};$('#assetSet').onchange=e=>{state.set=e.target.value;resetSelection()};$('#difficulty').onchange=e=>state.difficulty=e.target.value;$('#backBtn').onclick=renderMenu;$('#restartBtn').onclick=()=>state.game&&openGame(state.game);$('#helpBtn').onclick=help;$('#closeHelp').onclick=()=>$('#helpDialog').close();$('#resultAgain').onclick=()=>openGame(state.game);$('#resultMenu').onclick=renderMenu;$('#soundBtn').onclick=()=>{window.KCSoundCore?.unlock?.();const on=window.KCSoundCore?.toggle?.()??($('#soundBtn').getAttribute('aria-pressed')!=='true');$('#soundBtn').setAttribute('aria-pressed',String(on));$('#soundBtn').textContent=on?'🔊':'🔇';localStorage.setItem('kc-game-sound',String(on))};
$('#openAssetStudio').onclick=()=>{state.game=null;renderAssetStudio();$('#assetDialog').showModal()};$('#closeAssetStudio').onclick=()=>$('#assetDialog').close();$('#applyAssets').onclick=()=>{const pending=state.game,needed=pending?requiredAssetCount(pending):2;if(state.selected.size<needed){$('#assetStudioMessage').textContent=`Bitte mindestens ${needed} Motive markieren. Aktuell: ${state.selected.size}.`;return}$('#assetDialog').close();if(pending)openGame(pending)};$('#playerAsset').onchange=e=>state.player=e.target.value;$('#opponentAsset').onchange=e=>state.opponent=e.target.value;$('#selectAllAssets').onclick=()=>{state.selected=new Set(currentPool().map(x=>x.id));renderAssetStudio()};$('#clearAssets').onclick=()=>{state.selected=new Set();renderAssetStudio()};
$('#difficulty').innerHTML=Object.values(DIFFICULTIES).map(x=>`<option value="${x.id}">${x.label}</option>`).join('');$('#difficulty').value=state.difficulty;const soundOn=window.KCSoundCore?.isEnabled?.()??localStorage.getItem('kc-game-sound')!=='false';$('#soundBtn').setAttribute('aria-pressed',String(soundOn));$('#soundBtn').textContent=soundOn?'🔊':'🔇';renderEdition();resetSelection();renderMenu();const directGame=location.hash.slice(1);if(GAMES[directGame]&&unlocked(directGame))openGame(directGame);
