if(typeof document!=='undefined'&&!document.querySelector('link[data-maze-v3]')){const style=document.createElement('link');style.rel='stylesheet';style.href='./maze-v3.css?v=3.0.0';style.dataset.mazeV3='';document.head.append(style)}
const SCENARIOS=Object.freeze([
 {from:'🐕',fromLabel:'Hund',to:'🦴',toLabel:'Knochen',goalPhrase:'zum Knochen'},
 {from:'🎣',fromLabel:'Angler',to:'🐟',toLabel:'Fisch',goalPhrase:'zum Fisch'},
 {from:'👨‍🍳',fromLabel:'Koch',to:'🥩',toLabel:'Steak',goalPhrase:'zum Steak'},
 {from:'🥖',fromLabel:'Bäcker',to:'🥨',toLabel:'Brezel',goalPhrase:'zur Brezel'},
 {from:'🐁',fromLabel:'Maus',to:'🧀',toLabel:'Käse',goalPhrase:'zum Käse'},
 {from:'🐿️',fromLabel:'Eichhörnchen',to:'🌰',toLabel:'Nuss',goalPhrase:'zur Nuss'},
 {from:'🚿',fromLabel:'Gießkanne',to:'🌻',toLabel:'Blume',goalPhrase:'zur Blume'},
 {from:'🐈',fromLabel:'Katze',to:'🧶',toLabel:'Wollknäuel',goalPhrase:'zum Wollknäuel'},
 {from:'🐇',fromLabel:'Kaninchen',to:'🥕',toLabel:'Möhre',goalPhrase:'zur Möhre'},
 {from:'🐝',fromLabel:'Biene',to:'🍯',toLabel:'Honig',goalPhrase:'zum Honig'}
]);
const LETTERS=['A','B','C'];
const shuffle=a=>{a=[...a];for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const ROUTES={
 easy:[[[8,50],[27,50],[27,28],[52,28],[52,50]],[[8,50],[23,50],[23,72],[40,72],[40,62]],[[8,50],[18,50],[18,15],[38,15],[38,24]]],
 normal:[[[8,50],[20,50],[20,20],[35,20],[35,68],[48,68],[48,50],[52,50]],[[8,50],[17,50],[17,78],[32,78],[32,38],[43,38],[43,27]],[[8,50],[25,50],[25,32],[42,32],[42,80],[57,80],[57,67]]],
 pro:[[[8,50],[16,50],[16,16],[29,16],[29,76],[41,76],[41,31],[53,31],[53,50],[52,50]],[[8,50],[21,50],[21,82],[34,82],[34,25],[45,25],[45,67],[58,67],[58,75]],[[8,50],[13,50],[13,27],[25,27],[25,70],[37,70],[37,14],[49,14],[49,38],[60,38],[60,27]]]
};
const points=route=>route.map(([x,y])=>`${x},${y}`).join(' ');

export class MazeGame{
 constructor(ctx){Object.assign(this,ctx);this.timers=[]}
 start(){this.mode=null;this.host.className='game-board maze-stage';this.host.innerHTML=`<div class="maze-intro"><small>KC SPIELEWELT</small><h2>KC LABYRINTH</h2><p>Zehn Aufgaben · drei Wege · nur einer erreicht das Ziel.</p><div><button data-mode="solo" class="primary">Allein spielen</button><button data-mode="computer">Gegen Computer</button></div></div>`;this.host.querySelectorAll('[data-mode]').forEach(button=>button.onclick=()=>this.begin(button.dataset.mode));this.status({score:0,round:1,message:'Wähle: allein spielen oder gegen den Computer.'})}
 begin(mode){this.mode=mode;this.round=0;this.score=0;this.correct=0;this.computerScore=0;this.totalStarted=Date.now();this.scenarios=shuffle(SCENARIOS);this.next()}
 next(){if(this.round>=this.scenarios.length)return this.complete();this.scenario=this.scenarios[this.round];this.answer=LETTERS[Math.floor(Math.random()*3)];this.answered=false;this.roundStarted=Date.now();this.render();this.status({score:this.score,round:`${this.round+1}/10`,message:`Welcher Weg führt ${this.scenario.fromLabel} ${this.scenario.goalPhrase}? A, B oder C?`});if(this.mode==='computer')this.computerTurn()}
 routeFor(letter,correct){const level={easy:1,normal:2,pro:3}[this.difficulty],extra=level+(this.round>=2?1:0)+(this.round>=6?1:0),v=(this.round||0)%5;if(letter==='A'){const route=[[8,20],[18+v,20],[18+v,9],[34,9],[34,29],[47+v,29]];if(extra>1)route.push([47+v,14],[61,14],[61,32]);if(extra>2)route.push([73,32],[73,18],[82,18]);if(extra>3)route.push([82,34]);route.push([88,34]);if(correct)route.push([88,50],[94,50]);return route}if(letter==='C'){const route=[[8,80],[18+v,80],[18+v,91],[34,91],[34,71],[47+v,71]];if(extra>1)route.push([47+v,86],[61,86],[61,68]);if(extra>2)route.push([73,68],[73,82],[82,82]);if(extra>3)route.push([82,66]);route.push([88,66]);if(correct)route.push([88,50],[94,50]);return route}const route=[[8,50],[17+v,50],[17+v,40],[31,40],[31,59],[44+v,59]];if(extra>1)route.push([44+v,42],[57,42],[57,58]);if(extra>2)route.push([69,58],[69,43],[79,43]);if(extra>3)route.push([79,57]);route.push([88,57]);if(correct)route.push([88,50],[94,50]);return route}
 routeSet(){return LETTERS.map(letter=>this.routeFor(letter,letter===this.answer))}
 branches(){return []}
 render(){const routes=this.routeSet(),branches=this.branches();this.host.innerHTML=`<div class="maze-cabinet" data-difficulty="${this.difficulty}"><header><div><small>AUFGABE ${this.round+1} VON 10</small><strong>${this.scenario.from} ${this.scenario.fromLabel} zum ${this.scenario.toLabel} ${this.scenario.to}</strong></div><div class="maze-time"><span>Zeit</span><b data-maze-time>00:00</b></div></header><div class="maze-arena"><div class="maze-start"><b>START</b><span>${this.scenario.from}</span></div><svg class="maze-map" viewBox="0 0 100 100" role="img" aria-label="Wandlabyrinth mit den Eingängen A, B und C"><rect class="maze-wall-field" width="100" height="100"/>${branches.map(branch=>`<polyline class="maze-branch" points="${points(branch)}"/>`).join('')}${routes.map((route,index)=>`<polyline class="maze-route route-${LETTERS[index]}" data-route="${LETTERS[index]}" points="${points(route)}"/>`).join('')}<path class="maze-target-gate" d="M94 44 L94 56 M94 50 L99 50"/></svg><div class="maze-goal"><b>ZIEL</b><span>${this.scenario.to}</span></div></div><div class="maze-question"><strong>Welcher Eingang führt zum Ziel?</strong><div>${LETTERS.map(letter=>`<button data-answer="${letter}">${letter}</button>`).join('')}</div><p data-computer-answer>${this.mode==='computer'?'Computer prüft das Labyrinth …':'Verfolge die freien Korridore ab A, B oder C.'}</p></div><div class="maze-score"><span>Richtig <b>${this.correct}/10</b></span><span>Punkte <b>${this.score}</b></span>${this.mode==='computer'?`<span>Computer <b>${this.computerScore}</b></span>`:''}</div></div>`;this.host.querySelectorAll('[data-answer]').forEach(button=>button.onclick=()=>this.choose(button.dataset.answer));this.tick();this.clock=setInterval(()=>this.tick(),250)}
 tick(){const node=this.host.querySelector('[data-maze-time]');if(node)node.textContent=this.format(Math.floor((Date.now()-this.roundStarted)/1000))}
 format(seconds){return`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`}
 computerTurn(){this.host.querySelectorAll('[data-answer]').forEach(button=>button.disabled=true);const accuracy={easy:.48,normal:.66,pro:.82}[this.difficulty],choice=Math.random()<accuracy?this.answer:shuffle(LETTERS.filter(x=>x!==this.answer))[0];this.computerChoice=choice;this.timers.push(setTimeout(()=>{const node=this.host.querySelector('[data-computer-answer]');if(node)node.textContent=`Computer wählt Weg ${choice}. Jetzt bist du dran.`;this.host.querySelectorAll('[data-answer]').forEach(button=>button.disabled=false)},650))}
 choose(letter){if(this.answered)return;this.answered=true;clearInterval(this.clock);const seconds=Math.floor((Date.now()-this.roundStarted)/1000),right=letter===this.answer,timeBonus=Math.max(0,60-seconds)*2,difficultyBonus={easy:0,normal:60,pro:120}[this.difficulty];if(right){this.correct++;this.score+=100+timeBonus+difficultyBonus}if(this.mode==='computer'&&this.computerChoice===this.answer)this.computerScore+=100+Math.max(0,50-seconds);this.host.querySelectorAll('[data-answer]').forEach(button=>{button.disabled=true;button.classList.toggle('correct',button.dataset.answer===this.answer);button.classList.toggle('wrong',button.dataset.answer===letter&&!right)});this.host.querySelector(`[data-route="${this.answer}"]`)?.classList.add('solution');if(!right)this.host.querySelector(`[data-route="${letter}"]`)?.classList.add('false-choice');const info=this.host.querySelector('[data-computer-answer]');info.innerHTML=`${right?'Richtig!':'Leider falsch.'} Weg <b>${this.answer}</b> führt zum Ziel · ${this.format(seconds)} <button data-next>${this.round===9?'Ergebnis':'Nächstes Labyrinth'}</button>`;info.querySelector('[data-next]').onclick=()=>{this.round++;this.next()};this.status({score:this.score,round:`${this.round+1}/10`,message:right?`Richtig: Weg ${this.answer} · Zeitbonus ${timeBonus} Punkte.`:`Weg ${this.answer} wäre richtig gewesen.`})}
 complete(){clearInterval(this.clock);const total=Math.floor((Date.now()-this.totalStarted)/1000),won=this.mode!=='computer'||this.score>=this.computerScore;this.finish({score:this.score,achievement:this.correct>=8,message:`${this.correct} von 10 richtig · Gesamtzeit ${this.format(total)}${this.mode==='computer'?` · Computer ${this.computerScore} Punkte · ${won?'Du gewinnst!':'Computer gewinnt.'}`:''}`})}
 destroy(){clearInterval(this.clock);this.timers.forEach(clearTimeout)}
}

export {SCENARIOS};
